import { useQuery } from "@tanstack/react-query";
import {
  Box, Dialog, DialogTitle, DialogContent, DialogActions, Typography, Button, Chip,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, alpha,
} from "@mui/material";
import { axiosInstance } from "@/api/axios";
import { SEMANTIC } from "@/styles/accents";
import ErrorState from "@/components/ErrorState";
import { ListSkeleton } from "@/components/TableRowsSkeleton";
import { apiErrorText } from "@/utils/apiError";

const HEAD_SX = { fontWeight: 700, textTransform: "none", letterSpacing: "normal", fontSize: "inherit", color: "inherit" } as const;

interface Props {
  /** The PO to show; null closes the dialog. */
  purchaseOrderId: string | null;
  onClose: () => void;
}

const statusColor = (status: string) =>
  status === "pending" ? SEMANTIC.warning : status === "partial" ? SEMANTIC.info : SEMANTIC.success;

const StatusPill = ({ status }: { status: string }) => (
  <Box sx={{
    display: "inline-block", px: 1.25, py: 0.25, borderRadius: 2, fontSize: "0.75rem", fontWeight: 700,
    bgcolor: alpha(statusColor(status), 0.12), color: statusColor(status),
  }}>
    {status.toUpperCase()}
  </Box>
);

/**
 * Read-only history for one purchase order: what was ordered, how much has
 * actually been received, under which batch/expiry, and — the part that
 * answers "I received it, so where did it go?" — the batch that stock landed
 * in plus the medicine's resulting total across all batches.
 */
export default function PurchaseOrderDetailDialog({ purchaseOrderId, onClose }: Props) {
  const { data, isLoading, isError, error, refetch } = useQuery({
    queryKey: ["purchase-order-detail", purchaseOrderId],
    queryFn: async () => (await axiosInstance.get(`/pharmacy/purchase-orders/${purchaseOrderId}`)).data.data,
    enabled: !!purchaseOrderId,
  });

  return (
    <Dialog open={!!purchaseOrderId} onClose={onClose} maxWidth="lg" fullWidth>
      <DialogTitle sx={{ display: "flex", alignItems: "center", gap: 1.5, flexWrap: "wrap" }}>
        Purchase Order {purchaseOrderId?.split("-")[0].toUpperCase()}
        {data && <StatusPill status={data.status} />}
        {data?.isAutoGenerated && (
          <Chip label="auto-generated" size="small" sx={{ height: 20, fontSize: "0.65rem", fontWeight: 700 }} />
        )}
      </DialogTitle>
      <DialogContent dividers>
        {isLoading ? (
          <ListSkeleton rows={4} />
        ) : isError || !data ? (
          <ErrorState message={apiErrorText(error)} onRetry={() => refetch()} />
        ) : (
          <Box sx={{ display: "flex", flexDirection: "column", gap: 2.5 }}>
            <Box sx={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
              <Box>
                <Typography variant="caption" sx={{ color: "text.secondary", fontWeight: 600 }}>SUPPLIER</Typography>
                <Typography variant="body2" sx={{ fontWeight: 600 }}>{data.supplierName || "Unassigned"}</Typography>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: "text.secondary", fontWeight: 600 }}>ORDER DATE</Typography>
                <Typography variant="body2" sx={{ fontWeight: 600 }}>{new Date(data.orderDate).toLocaleDateString()}</Typography>
              </Box>
              <Box>
                <Typography variant="caption" sx={{ color: "text.secondary", fontWeight: 600 }}>RECEIVED</Typography>
                <Typography variant="body2" sx={{ fontWeight: 700, color: data.totalReceived >= data.totalOrdered ? "success.main" : "warning.main" }}>
                  {data.totalReceived} / {data.totalOrdered} units
                </Typography>
              </Box>
            </Box>

            <TableContainer>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell sx={HEAD_SX}>Medicine</TableCell>
                    <TableCell sx={HEAD_SX} align="right">Ordered</TableCell>
                    <TableCell sx={HEAD_SX} align="right">Received</TableCell>
                    <TableCell sx={HEAD_SX} align="right">Outstanding</TableCell>
                    <TableCell sx={HEAD_SX}>Received into batch</TableCell>
                    <TableCell sx={HEAD_SX} align="right">Batch qty now</TableCell>
                    <TableCell sx={HEAD_SX} align="right">Medicine total</TableCell>
                    <TableCell sx={HEAD_SX}>Status</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {data.items.map((item: any) => (
                    <TableRow key={item.purchaseOrderItemId}>
                      <TableCell>
                        <Typography variant="body2" sx={{ fontWeight: 600 }}>{item.medicineName}</Typography>
                        {item.genericName && (
                          <Typography variant="caption" sx={{ color: "text.secondary" }}>{item.genericName}</Typography>
                        )}
                      </TableCell>
                      <TableCell align="right">{item.orderedQuantity}</TableCell>
                      <TableCell align="right" sx={{ fontWeight: 700, color: item.receivedQuantity > 0 ? "success.main" : "text.secondary" }}>
                        {item.receivedQuantity}
                      </TableCell>
                      <TableCell align="right" sx={{ color: item.outstandingQuantity > 0 ? "warning.main" : "text.secondary" }}>
                        {item.outstandingQuantity}
                      </TableCell>
                      <TableCell>
                        {item.receivedBatchNumber ? (
                          <>
                            <Typography variant="body2" sx={{ fontWeight: 600 }}>{item.receivedBatchNumber}</Typography>
                            {item.receivedExpiryDate && (
                              <Typography variant="caption" sx={{ color: "text.secondary" }}>
                                exp {new Date(item.receivedExpiryDate).toLocaleDateString()}
                              </Typography>
                            )}
                          </>
                        ) : (
                          <Typography variant="caption" sx={{ color: "text.secondary" }}>Not received yet</Typography>
                        )}
                      </TableCell>
                      <TableCell align="right" sx={{ color: "text.secondary" }}>
                        {item.batchQuantityNow == null ? "—" : item.batchQuantityNow}
                      </TableCell>
                      <TableCell align="right" sx={{ fontWeight: 700 }}>{item.medicineTotalStock}</TableCell>
                      <TableCell><StatusPill status={item.status} /></TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>

            <Typography variant="caption" sx={{ color: "text.secondary" }}>
              "Batch qty now" is what remains in that specific batch today (dispensing reduces it).
              "Medicine total" is the medicine's usable stock across every non-expired batch — the
              figure the Current Stock tab's "Total (all batches)" column shows.
            </Typography>
          </Box>
        )}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>Close</Button>
      </DialogActions>
    </Dialog>
  );
}
