// Shared domain types for the HMS frontend.
//
// These mirror the API response shapes and exist to replace the pervasive `any`
// in the logic-heavy flows (pharmacy POS, billing, inventory). Adopt them
// incrementally: type a page's state with these instead of `any[]`.

/** Standard API envelope used across the backend. */
export interface ApiResponse<T> {
  status: "success" | "error";
  data: T;
  message?: string;
}

/** Pagination envelope returned when a `?page=` query is supplied. */
export interface Pagination {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination: Pagination;
}

// ── Pharmacy ────────────────────────────────────────────────
export interface Medicine {
  medicineId: string;
  hospitalId: string | null;
  medicineCode: string;
  medicineName: string | null;
  genericName: string;
  manufacturer: string;
  sellingPrice: string | number;
  minStockLevel: number;
  defaultSupplierId: string | null;
}

export interface Supplier {
  supplierId: string;
  hospitalId: string | null;
  supplierCode: string;
  supplierName: string | null;
  contactPersonName: string;
  phone: string;
  email: string;
  gstNumber: string;
  city: string;
  state: string;
  country: string;
}

export interface MedicineInventory {
  inventoryId: string;
  hospitalId: string | null;
  medicineId: string | null;
  supplierId: string | null;
  batchNumber: string;
  expiryDate: string;
  availableQuantity: number;
  reorderLevel: number;
}

export interface PurchaseOrderItem {
  purchaseOrderItemId: string;
  purchaseOrderId: string;
  medicineId: string;
  orderedQuantity: number;
  receivedQuantity: number;
  unitPrice: string | number;
  totalPrice: string | number;
  batchNumber: string | null;
  expiryDate: string | null;
  status: string;
}

export interface PurchaseOrder {
  purchaseOrderId: string;
  hospitalId: string | null;
  supplierId: string | null;
  orderDate: string;
  status: string;
  isAutoGenerated: boolean;
  items: PurchaseOrderItem[];
}

export interface PharmacyOrderItem {
  pharmacyOrderItemId: string;
  pharmacyOrderId: string;
  medicineId: string;
  quantity: number;
  unitPrice: string | number;
  totalPrice: string | number;
}

export interface PharmacyOrder {
  pharmacyOrderId: string;
  hospitalId: string | null;
  prescriptionId: string | null;
  patientId: string | null;
  status: string;
  cancellationReason: string | null;
  paymentStatus: string;
  totalAmount: string | number | null;
  createdAt: string;
  items: PharmacyOrderItem[];
}

export interface LowStockAlert extends Medicine {
  currentStock: number;
  pendingStock: number;
}

/** A pending prescription as enriched by the pharmacy queue endpoint. */
export interface PendingPrescriptionItem {
  prescriptionItemId: string;
  prescriptionId: string | null;
  medicineId: string | null;
  medicineName: string;
  genericName: string;
  medicineCode: string;
  unitPrice: number;
  quantity: number;
  dosage: string;
  frequency: string;
  buyOutside: boolean;
}

export interface PendingPrescription {
  prescriptionId: string;
  patientId: string | null;
  prescriptionDate: string;
  dispensingStatus: string;
  items: PendingPrescriptionItem[];
  patientName: string | null;
  uhidNumber: string | null;
}

// ── Billing ─────────────────────────────────────────────────
export interface UnbilledItem {
  id: string;
  type: "CONSULTATION" | "LAB" | "RADIOLOGY" | "PHARMACY";
  description: string;
  amount: number;
  date: string;
  metadata?: unknown;
}
